### PR TITLE
fix: handle `Headers` when merging proxy headers 

### LINKED ISSUE #865: mergeHeaders unexpected behaviour / type issue
### Environment

`Nuxt 3.12.2 with Nitro 2.9.6`
development mode

### Reproduction

```ts
const headers = new Headers()
if (session.token)
    headers.set("Authorization", `Bearer ${session.token}`)
else
    console.warn(`[PROXY] No token set`)
if (session.domain)
    headers.set("X-Domain", session.domain)
else
    console.warn(`[PROXY] No domain set`)

// note: no 'Authorization' header in the event headers
const mergedHeaders = mergeHeaders(event.headers, headers)

console.log(mergedHeaders.get("Authorization"))
// log: undefined
```

### Describe the bug

The `mergeHeaders` utility won't merge multiple instances of Headers. This is a result of the underlying logic using Object.entries to get a list of key-value pairs which returns an empty array on a Headers instance.

Since `Headers` satisfies the `HeadersInit` type, this should either work, or the types should be changed appropriately.
Once it's clear how we should continue, I will open a PR.

### Additional context

I found this issue when trying to use the proxyRequest / sendProxy utility, basically all of the other utilities depending on mergeHeaders suffer from the type / logic issue and it's not that trivial to find, because you think something is wrong in your code.

### Logs

_No response_

### PR DESCRIPTION
**Pull request by kricsleo**
resolves #865

This backports the fix to v1. (see #1026 for v2)
If it's not needed, feel free to close it. ❤️

### CODE REVIEW

File: src/utils/proxy.ts [hunk 1]
```diff
@@ -259,9 +259,14 @@ function mergeHeaders(
...
-    for (const [key, value] of Object.entries(input!)) {
+    const entries = Array.isArray(input)
+      ? input
+      : typeof input.entries === "function"
+        ? input.entries()
+        : Object.entries(input);
+    for (const [key, value] of entries) {
       if (value !== undefined) {
-        merged.set(key, value);
+        merged.set(key.toString(), value);
```
Comment (pi0) [inline src/utils/proxy.ts:269]: Can you please update same as #1026

Comment (kricsleo) [reply src/utils/proxy.ts]: Done
